### ISSUE TITLE
LaunchWrapper fails on Java 9.

### ISSUE THREAD

**Issue by dscalzi** [Mojang/LegacyLauncher#20]
Issue when loading:

```
Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Location in code:
https://github.com/Mojang/LegacyLauncher/blob/master/src/main/java/net/minecraft/launchwrapper/Launch.java#L34

**Comment by kashike** [comment]
#11

**Comment by FinnT730** [comment]
Can I say one thing?
Look at the last commit! And this is the old Minecraft launcher!!


(If I don't repay to this, it doesn't mean I dislike the feedback or anything, but I get like 200+ mail's of github, and I don't even look in my Github inbox anymore!)

**Comment by liach** [comment]
@FinnT730 Go to your user settings to fix the mails. You can let github only send mails about those threads that you actually participated in.

**Comment by SeasonalFerret** [comment]
Issue seems to persist on Java 10.

**Comment by liach** [comment]
As long as the module system is there, the issue exists.

**Comment by mjrb** [comment]
I found a temporary fix, you can manually download and unzip [jre8](https://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html) and if you enable advanced options in the launcher you can specify the path to java. you give it `<path to unziped jre8>/bin/java`. this worked for me when I was trying to use forge for minecraft 1.10 on ubuntu 18.04

**Comment by elouejmajdi** [comment]
> rsist on Java 10.

I got the same issue when I use JDK 12

**Comment by dscalzi** [comment]
This project won't support versions later than Java 8. Use modlauncher with the latest versions of minecraft.

**Comment by DesertCookie** [comment]
This issue seems to also appear on Eclipse Temurin JDK 1.8:

```
java.lang.NullPointerException: null
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_392]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_392]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```
