### ISSUE TITLE
Update to current verison?

### ISSUE THREAD

**Issue by scholzi100** [Mojang/LegacyLauncher#28]
Hi, as I see this project has not been updated in a long time. But since it was continued Mojang internally an is still in use. As well as source could be obtained thru libraries.minecraft.net.

Will there be any update to it?

Are there any plans toward a licence? ( #1 )

**Comment by Pokechu22** [comment]
I'm not sure what you mean by continued internally.  The latest version specified in build.gradle is 1.12, corresponding to https://libraries.minecraft.net/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar.  I can't find any newer version; no larger version number I can think of exists (I tried [1.12.1](https://libraries.minecraft.net/net/minecraft/launchwrapper/1.12.1/launchwrapper-1.12.1.jar), [1.13](https://libraries.minecraft.net/net/minecraft/launchwrapper/1.13/launchwrapper-1.13.jar), and [1.14](https://libraries.minecraft.net/net/minecraft/launchwrapper/1.14/launchwrapper-1.14.jar)).  In fact, I see the opposite &mdash; the vanilla versions I checked all use version 1.5 instead (e.g. [beta 1.7.3](https://launchermeta.mojang.com/v1/packages/66cafaf8ea5a7b76547eb24c848832af44255ba1/b1.7.3.json))

To my understanding, forge is slowly migrating to [modlauncher](https://github.com/cpw/modlauncher), which is in (slow) development.  I don't know much about the status of that.
