### ISSUE TITLE
Launch Alpha differently

### ISSUE THREAD

**Issue by TorutheRedFox** [Mojang/LegacyLauncher#31]
The way that Alpha versions are loaded makes them not read the username and session ID passed to them.
I suspect this is because of the game being loaded from net.minecraft.client.Minecraft, rather than net.minecraft.client.MinecraftApplet like the original launcher did. I'm not sure why the main function doesn't get the arguments, but it just doesn't. (args length is 0?)

EDIT: I just looked into the main function. Turns out that it overwrites the username with "Player524" no matter what, so basically, launching the game through net.minecraft.client.Minecraft is a no-go, as it's for debugging only, with the game being intended to be launched through the applet class instead.

EDIT 2: it's caused by a missing argument in the JSONs. That should be fixed there instead

**Comment by aprilthepink** [comment]
sus bump
